apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tr6ig54eo-java-quarkus
  janus-idp.io/tekton: tr6ig54eo-java-quarkus
  backstage.io/kubernetes-id: tr6ig54eo-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tr6ig54eo-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
